export const FIND_STORAGE_BY_ID = "FIND_STORAGE_BY_ID";
export const FIND_ALL_STORAGES = "FIND_ALL_STORAGES";
export const SAVE_STORAGE = "SAVE_STORAGE";
export const DELETE_STORAGE_BY_ID = "DELETE_STORAGE_BY_ID";
export const STORAGE_PROMISE = "STORAGE_PROMISE";
