export const FIND_PHARMACIST_BY_ID = "FIND_PHARMACIST_BY_ID";
export const FIND_ALL_PHARMACISTS = "FIND_ALL_PHARMACISTS";
export const SAVE_PHARMACIST = "SAVE_PHARMACIST";
export const DELETE_PHARMACIST_BY_ID = "DELETE_PHARMACIST_BY_ID";
export const PHARMACIST_PROMISE = "PHARMACIST_PROMISE";
